name: deploy-frontend

on:
  pull_request:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_REGION: ${{ env.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
      - name: Build frontend
        working-directory: ./packages/frontend
        if: ${{ github.event_name != 'workflow_call' }}
        run: pnpm build
      - name: Download build
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: frontend
          path: ./packages/frontend/build
      - name: Generate module and provider bindings
        run: pnpm cdktf-cli get
      - name: Test the synth
        uses: hashicorp/terraform-cdk-action@v5
        with:
          cdktfVersion: 0.20.9
          terraformVersion: 1.9.8
          mode: synth-only
          stackName: frontend
