name: pull-request-checks

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  compile-backend:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
      - name: Run type checker
        working-directory: backend
        run: pnpm tsc -b
  compile-frontend:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
      - name: Run type checker
        working-directory: frontend
        run: pnpm tsc -b

  lint:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
      - name: Run linter
        id: lint
        run: pnpm run lint --fix
      - name: Commit and push fixed files
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        if: steps.lint.outcome == 'failure' && github.event_name == 'pull_request'
        with:
          add: ./src
          message: Fix lint issues

  test:
    runs-on: self-hosted
    steps:
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
      - name: Run tests
        run: pnpm -r run test


  knip:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
      - name: Knip code
        run: pnpm knip
